/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : McuEvents.c
**     Project     : FRDM-K64F_Generator
**     Processor   : MK64FN1M0VLL12
**     Component   : SimpleEvents
**     Version     : Component 01.054, Driver 01.00, CPU db: 3.00.000
**     Repository  : Legacy User Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2016-12-10, 11:39, # CodeGen: 92
**     Abstract    :
**
**     Settings    :
**          Component name                                 : McuEvents
**          SDK                                            : McuLib
**          Critical Section                               : McuCriticalSection
**          Initialize on Init                             : yes
**          Event Name List                                : (string list)
**          Power Save                                     : no
**          Low Power                                      : Disabled
**     Contents    :
**         SetEvent      - void McuEvents_SetEvent(uint8_t event);
**         ClearEvent    - void McuEvents_ClearEvent(uint8_t event);
**         EventsPending - bool McuEvents_EventsPending(void);
**         GetEvent      - bool McuEvents_GetEvent(uint8_t event);
**         GetClearEvent - bool McuEvents_GetClearEvent(uint8_t event);
**         HandleEvent   - void McuEvents_HandleEvent(void);
**
**     * Copyright (c) 2011-2016, Erich Styger
**      * Web:         https://mcuoneclipse.com
**      * SourceForge: https://sourceforge.net/projects/mcuoneclipse
**      * Git:         https://github.com/ErichStyger/McuOnEclipse_PEx
**      * All rights reserved.
**      *
**      * Redistribution and use in source and binary forms, with or without modification,
**      * are permitted provided that the following conditions are met:
**      *
**      * - Redistributions of source code must retain the above copyright notice, this list
**      *   of conditions and the following disclaimer.
**      *
**      * - Redistributions in binary form must reproduce the above copyright notice, this
**      *   list of conditions and the following disclaimer in the documentation and/or
**      *   other materials provided with the distribution.
**      *
**      * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**      * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**      * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**      * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**      * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**      * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**      * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**      * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**      * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**      * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file McuEvents.c
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup McuEvents_module McuEvents module documentation
**  @{
*/         

/* MODULE McuEvents. */
#ifndef __HIWARE__
  #include <stdbool.h>
  #include <stdint.h>
#endif
#include "McuEvents.h"
#if McuLib_SDK_VERSION_USED == McuLib_SDK_VERSION_NONE
  #include "Events.h"
#endif


#define McuEvents_NOF_EVENTS  1         /*!< Number of events supported */
static uint8_t McuEvents_Events[((McuEvents_NOF_EVENTS-1)/8)+1]; /*!< Bit set of events */
/*
** ===================================================================
**     Method      :  McuEvents_SetEvent (component SimpleEvents)
**     Description :
**         Sets an event (number) be processed by the next HandleEvent()
**         call
**     Parameters  :
**         NAME            - DESCRIPTION
**         event           - The event (number) to be set so it
**                           will be called by the HandleEvent() routine
**                           later on. Note that there cannot be
**                           multiple instances of an event, and the
**                           lower the event number, the higher the
**                           priority.
**     Returns     : Nothing
** ===================================================================
*/
void McuEvents_SetEvent(uint8_t event)
{
  McuCriticalSection_CriticalVariable();

  /* event is in the range of 0..255: find bit position in array */
  McuCriticalSection_EnterCritical();
  McuEvents_Events[event/8] |= 0x80>>(event%8);
  McuCriticalSection_ExitCritical();
}

/*
** ===================================================================
**     Method      :  McuEvents_ClearEvent (component SimpleEvents)
**     Description :
**         Clears one event (number). If the event is not set, then the
**         function has no effect.
**     Parameters  :
**         NAME            - DESCRIPTION
**         event           - The event number to be cleared.
**     Returns     : Nothing
** ===================================================================
*/
void McuEvents_ClearEvent(uint8_t event)
{
  McuCriticalSection_CriticalVariable();

 /* event is in the range of 0..255: find bit position in array */
  McuCriticalSection_EnterCritical();
  McuEvents_Events[event/8] &= ~(0x80>>(event%8));
  McuCriticalSection_ExitCritical();
}

/*
** ===================================================================
**     Method      :  McuEvents_GetEvent (component SimpleEvents)
**     Description :
**         Allows to check if an event is set or not.
**     Parameters  :
**         NAME            - DESCRIPTION
**         event           - The event number to check. If the
**                           event is set, the function returns TRUE.
**     Returns     :
**         ---             - none
** ===================================================================
*/
bool McuEvents_GetEvent(uint8_t event)
{
  /* event is in the range of 0..255: find bit position in array */
  return (bool)(McuEvents_Events[event/8]&(0x80>>(event%8)));
}

/*
** ===================================================================
**     Method      :  McuEvents_GetClearEvent (component SimpleEvents)
**     Description :
**         Allows to check if an event is set or not. If set, it will
**         be automatically cleared.
**     Parameters  :
**         NAME            - DESCRIPTION
**         event           - The event number to check. If the
**                           event is set, the function returns TRUE.
**     Returns     :
**         ---             - none
** ===================================================================
*/
bool McuEvents_GetClearEvent(uint8_t event)
{
  bool isSet = FALSE;
  McuCriticalSection_CriticalVariable();

  McuCriticalSection_EnterCritical();
  if (McuEvents_GetEvent(event)) { /* event present */
    McuEvents_Events[event/8] &= ~(0x80>>(event%8)); /* clear event */
    isSet = TRUE;
  }
  McuCriticalSection_ExitCritical();
  return isSet;
}

/*
** ===================================================================
**     Method      :  McuEvents_EventsPending (component SimpleEvents)
**     Description :
**         Returns true if any events are pending, false otherwise
**     Parameters  : None
**     Returns     :
**         ---             - True in case any events are pending, false
**                           otherwise.
** ===================================================================
*/
bool McuEvents_EventsPending(void)
{
  return (bool)(McuEvents_Events[0]!=0);
}

/*
** ===================================================================
**     Method      :  McuEvents_HandleEvent (component SimpleEvents)
**     Description :
**         Event handler, to be called periodically.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/
void McuEvents_HandleEvent(void)
{
  /* Handle the one with the highest priority. */
  uint8_t event;
  McuCriticalSection_CriticalVariable();

  McuCriticalSection_EnterCritical();
  for (event=0; event<McuEvents_NOF_EVENTS; event++) { /* does a test on every event */
    if (McuEvents_GetEvent(event)) { /* event present */
      McuEvents_Events[event/8] &= ~(0x80>>(event%8)); /* clear event */
      break; /* get out of loop */
    }
  }
  McuCriticalSection_ExitCritical();
  /*lint -save -e522 function lacks side effect  */
  if (event != McuEvents_NOF_EVENTS) {
    McuEvents_AppHandleEvent(event);
  }
  /*lint -restore */
}

/*
** ===================================================================
**     Method      :  McuEvents_Init (component SimpleEvents)
**
**     Description :
**         Initialization method.
**         This method is internal. It is used by Processor Expert only.
** ===================================================================
*/
void McuEvents_Init(void)
{
  McuEvents_Events[0] = 0; /* initialize data structure */
}

/* END McuEvents. */

/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
