/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : McuFontDisplay.h
**     Project     : FRDM-K64F_Generator
**     Processor   : MK64FN1M0VLL12
**     Component   : FontDisplay
**     Version     : Component 01.196, Driver 01.00, CPU db: 3.00.000
**     Repository  : Legacy User Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-08-18, 11:04, # CodeGen: 224
**     Abstract    :
**
**     Settings    :
**          Component name                                 : McuFontDisplay
**          System                                         : 
**            Display                                      : McuGDisplay
**            Font                                         : McuFontCour14Normal
**          Watchdog                                       : Disabled
**     Contents    :
**         GetFontHeight   - void McuFontDisplay_GetFontHeight(McuFontDisplay_Font *font,...
**         GetStringHeight - McuFontDisplay_PixelDim McuFontDisplay_GetStringHeight(byte *str,...
**         GetCharWidth    - void McuFontDisplay_GetCharWidth(byte ch, McuFontDisplay_PixelDim *charWidth,...
**         GetStringWidth  - McuFontDisplay_PixelDim McuFontDisplay_GetStringWidth(byte *str,...
**         WriteString     - void McuFontDisplay_WriteString(byte *str, McuFontDisplay_PixelColor color,...
**         WriteChar       - void McuFontDisplay_WriteChar(byte ch, McuFontDisplay_PixelColor color,...
**
**     * Copyright (c) 2011-2017, Erich Styger
**      * Web:         https://mcuoneclipse.com
**      * SourceForge: https://sourceforge.net/projects/mcuoneclipse
**      * Git:         https://github.com/ErichStyger/McuOnEclipse_PEx
**      * All rights reserved.
**      *
**      * Redistribution and use in source and binary forms, with or without modification,
**      * are permitted provided that the following conditions are met:
**      *
**      * - Redistributions of source code must retain the above copyright notice, this list
**      *   of conditions and the following disclaimer.
**      *
**      * - Redistributions in binary form must reproduce the above copyright notice, this
**      *   list of conditions and the following disclaimer in the documentation and/or
**      *   other materials provided with the distribution.
**      *
**      * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**      * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**      * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**      * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**      * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**      * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**      * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**      * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**      * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**      * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file McuFontDisplay.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup McuFontDisplay_module McuFontDisplay module documentation
**  @{
*/         

#ifndef __McuFontDisplay_H
#define __McuFontDisplay_H

/* MODULE McuFontDisplay. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "McuGDisplay.h"
#include "McuFontCour14Normal.h"

#include "Cpu.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef McuGDisplay_PixelDim   McuFontDisplay_PixelDim; /* type which can hold a integral type for the x/y pixel dimension. This is depending on the display used. */
typedef McuGDisplay_PixelColor McuFontDisplay_PixelColor; /* Type definining the color type (depens on display used). */
typedef GFONT_Callbacks McuFontDisplay_Font; /* Pointer to GFONT_Callbacks */




void McuFontDisplay_WriteString(byte *str, McuFontDisplay_PixelColor color, McuFontDisplay_PixelDim *xCursor, McuFontDisplay_PixelDim *yCursor, McuFontDisplay_Font *font);
/*
** ===================================================================
**     Method      :  McuFontDisplay_WriteString (component FontDisplay)
**     Description :
**         Function to write a string or character at the startpoint.
**         Set the startpoint with the function setCursor.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to the character string
**         color           - Foreground color to be used (for the
**                           character pixels)
**       * xCursor         - Pointer to x position of first
**                           character (upper left corner). On return
**                           this will contain the next y position.
**       * yCursor         - Pointer to y position of character
**                           (upper left corner). On return this will
**                           contain the next y position.
**       * font            - Pointer to font information
**     Returns     : Nothing
** ===================================================================
*/

void McuFontDisplay_WriteChar(byte ch, McuFontDisplay_PixelColor color, McuFontDisplay_PixelDim *xCursor, McuFontDisplay_PixelDim *yCursor, McuFontDisplay_Font *font);
/*
** ===================================================================
**     Method      :  McuFontDisplay_WriteChar (component FontDisplay)
**     Description :
**         Function to write a character at the start point. Set the
**         start point with the function setCursor.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - the character to print
**         color           - Foreground color to be used (for the
**                           character pixels)
**       * xCursor         - Pointer to x position of character
**                           (upper left corner). On return this will
**                           contain the next x position.
**       * yCursor         - Pointer to y position of character
**                           (upper left corner). On return this will
**                           contain the next y position.
**       * font            - Pointer to font information
**     Returns     : Nothing
** ===================================================================
*/

void McuFontDisplay_GetCharWidth(byte ch, McuFontDisplay_PixelDim *charWidth, McuFontDisplay_PixelDim *totalWidth, McuFontDisplay_Font *font);
/*
** ===================================================================
**     Method      :  McuFontDisplay_GetCharWidth (component FontDisplay)
**     Description :
**         returns the width (in pixels) of a font character.
**     Parameters  :
**         NAME            - DESCRIPTION
**         ch              - character for which to calculate the width
**       * charWidth       - Pointer to width of the
**                           character in pixels (this is only for the
**                           character, without the space after the
**                           character)
**       * totalWidth      - Pointer to the total width
**                           of the character, including to the space
**                           after the character.
**       * font            - Pointer to font information
**     Returns     : Nothing
** ===================================================================
*/

McuFontDisplay_PixelDim McuFontDisplay_GetStringWidth(byte *str, McuFontDisplay_Font *font, McuFontDisplay_PixelDim *lastCharSpace);
/*
** ===================================================================
**     Method      :  McuFontDisplay_GetStringWidth (component FontDisplay)
**     Description :
**         returns the width (in pixels) of a font string. For multiple
**         line strings (separated by \
**         ) or for strings with \r it returns the longest string
**         length.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to the string.
**       * font            - Pointer to font information
**       * lastCharSpace   - Pointer to the width
**                           of the last character space, useful if you
**                           combine multiple strings. The pointer may
**                           be NULL.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

void McuFontDisplay_GetFontHeight(McuFontDisplay_Font *font, McuFontDisplay_PixelDim *charHeight, McuFontDisplay_PixelDim *totalHeight);
/*
** ===================================================================
**     Method      :  McuFontDisplay_GetFontHeight (component FontDisplay)
**     Description :
**         returns the height (in pixels) of a font.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * font            - Pointer to font information
**       * charHeight      - Pointer to height of the
**                           character in pixels.
**       * totalHeight     - Pointer to the total
**                           height of the character, including to the
**                           space below the character.
**     Returns     : Nothing
** ===================================================================
*/

McuFontDisplay_PixelDim McuFontDisplay_GetStringHeight(byte *str, McuFontDisplay_Font *font, McuFontDisplay_PixelDim *lastLineSpace);
/*
** ===================================================================
**     Method      :  McuFontDisplay_GetStringHeight (component FontDisplay)
**     Description :
**         returns the height (in pixels) of a font string. For
**         multiple line strings (separated by newline) or for strings
**         with \r it returns the longest list.
**     Parameters  :
**         NAME            - DESCRIPTION
**       * str             - Pointer to the string.
**       * font            - Pointer to font information
**       * lastLineSpace   - Pointer to the height
**                           of the last line space, useful if you
**                           combine multiple strings. The pointer may
**                           be NULL.
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

/* END McuFontDisplay. */

#ifdef __cplusplus
}
#endif

#endif
/* ifndef __McuFontDisplay_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
