/* ###################################################################
**     This component module is generated by Processor Expert. Do not modify it.
**     Filename    : McuGDisplay.h
**     Project     : FRDM-K64F_Generator
**     Processor   : MK64FN1M0VLL12
**     Component   : GDisplay
**     Version     : Component 01.193, Driver 01.00, CPU db: 3.00.000
**     Repository  : Legacy User Components
**     Compiler    : GNU C Compiler
**     Date/Time   : 2017-03-27, 17:36, # CodeGen: 162
**     Abstract    :
**
**     Settings    :
**          Component name                                 : McuGDisplay
**          Inverted Pixels                                : no
**          Memory Buffer                                  : Enabled
**            Orientation                                  : Landscape
**          Clear screen on Init                           : no
**          Hardware                                       : 
**            Display                                      : McuSharpMemoryDisplay
**          Watchdog                                       : Disabled
**          RTOS                                           : Disabled
**     Contents    :
**         PutPixel          - void McuGDisplay_PutPixel(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y,...
**         SetPixel          - void McuGDisplay_SetPixel(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y);
**         ClrPixel          - void McuGDisplay_ClrPixel(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y);
**         Clear             - void McuGDisplay_Clear(void);
**         DrawBox           - void McuGDisplay_DrawBox(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y,...
**         DrawFilledBox     - void McuGDisplay_DrawFilledBox(McuGDisplay_PixelDim x, McuGDisplay_PixelDim...
**         DrawHLine         - void McuGDisplay_DrawHLine(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y,...
**         DrawVLine         - void McuGDisplay_DrawVLine(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y,...
**         DrawLine          - void McuGDisplay_DrawLine(McuGDisplay_PixelDim xstart, McuGDisplay_PixelDim...
**         DrawCircle        - void McuGDisplay_DrawCircle(McuGDisplay_PixelDim x0, McuGDisplay_PixelDim y0,...
**         DrawFilledCircle  - void McuGDisplay_DrawFilledCircle(McuGDisplay_PixelDim x0,...
**         DrawBarChart      - void McuGDisplay_DrawBarChart(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y,...
**         DrawMonoBitmap    - void McuGDisplay_DrawMonoBitmap(McuGDisplay_PixelDim x, McuGDisplay_PixelDim...
**         DrawColorBitmap   - void McuGDisplay_DrawColorBitmap(McuGDisplay_PixelDim x, McuGDisplay_PixelDim...
**         Draw65kBitmap     - void McuGDisplay_Draw65kBitmap(McuGDisplay_PixelDim x1, McuGDisplay_PixelDim...
**         Draw256BitmapLow  - void McuGDisplay_Draw256BitmapLow(McuGDisplay_PixelDim x1,...
**         Draw256BitmapHigh - void McuGDisplay_Draw256BitmapHigh(McuGDisplay_PixelDim x1,...
**         UpdateFull        - void McuGDisplay_UpdateFull(void);
**         UpdateRegion      - void McuGDisplay_UpdateRegion(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y,...
**         GetWidth          - McuGDisplay_PixelDim McuGDisplay_GetWidth(void);
**         GetHeight         - McuGDisplay_PixelDim McuGDisplay_GetHeight(void);
**         GetLongerSide     - McuGDisplay_PixelDim McuGDisplay_GetLongerSide(void);
**         GetShorterSide    - McuGDisplay_PixelDim McuGDisplay_GetShorterSide(void);
**         GetDisplay        - void McuGDisplay_GetDisplay(void);
**         GiveDisplay       - void McuGDisplay_GiveDisplay(void);
**         Init              - void McuGDisplay_Init(void);
**
**     * Copyright (c) 2013-2016, Erich Styger
**      * Web:         https://mcuoneclipse.com
**      * SourceForge: https://sourceforge.net/projects/mcuoneclipse
**      * Git:         https://github.com/ErichStyger/McuOnEclipse_PEx
**      * All rights reserved.
**      *
**      * Redistribution and use in source and binary forms, with or without modification,
**      * are permitted provided that the following conditions are met:
**      *
**      * - Redistributions of source code must retain the above copyright notice, this list
**      *   of conditions and the following disclaimer.
**      *
**      * - Redistributions in binary form must reproduce the above copyright notice, this
**      *   list of conditions and the following disclaimer in the documentation and/or
**      *   other materials provided with the distribution.
**      *
**      * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
**      * ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
**      * WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
**      * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR
**      * ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
**      * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
**      * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON
**      * ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
**      * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
**      * SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
** ###################################################################*/
/*!
** @file McuGDisplay.h
** @version 01.00
** @brief
**
*/         
/*!
**  @addtogroup McuGDisplay_module McuGDisplay module documentation
**  @{
*/         


#ifndef __McuGDisplay_H
#define __McuGDisplay_H

/* MODULE McuGDisplay. */

/* Include shared modules, which are used for whole project */
#include "PE_Types.h"
#include "PE_Error.h"
#include "PE_Const.h"
#include "IO_Map.h"
/* Include inherited beans */
#include "McuSharpMemoryDisplay.h"

#include "Cpu.h"


/* this type is declared in PE_Types.h for non-LDD processors, need to declare it locally otherwise */
typedef struct {                       /* Image */
  word width;                          /* Image width  */
  word height;                         /* Image height */
  const byte * pixmap;                 /* Image pixel bitmap */
  word size;                           /* Image size   */
  const char_t * name;                 /* Image name   */
} TIMAGE;
typedef TIMAGE* PIMAGE ;               /* Pointer to image */

#define McuGDisplay_RGB565(R,G,B)     ((McuGDisplay_PixelColor)((((R)&0x1f)<<11)+(((G)&0x3f)<<5)+((B)&0x1f))) /* convert RGB into 565 color format */

#define McuGDisplay_COLOR_PIXEL_SET          McuSharpMemoryDisplay_COLOR_PIXEL_SET       /* value for a pixel set */
#define McuGDisplay_COLOR_PIXEL_CLR          McuSharpMemoryDisplay_COLOR_PIXEL_CLR       /* value for a pixel cleared */
#define McuGDisplay_COLOR_BLACK              McuSharpMemoryDisplay_COLOR_BLACK           /* black color */
#define McuGDisplay_COLOR_WHITE              McuSharpMemoryDisplay_COLOR_WHITE           /* white color */
#define McuGDisplay_COLOR_RED                McuSharpMemoryDisplay_COLOR_RED             /* red color */
#define McuGDisplay_COLOR_BRIGHT_RED         McuSharpMemoryDisplay_COLOR_BRIGHT_RED      /* bright red color */
#define McuGDisplay_COLOR_DARK_RED           McuSharpMemoryDisplay_COLOR_DARK_RED        /* dark red color */
#define McuGDisplay_COLOR_GREEN              McuSharpMemoryDisplay_COLOR_GREEN           /* green color */
#define McuGDisplay_COLOR_DARK_GREEN         McuSharpMemoryDisplay_COLOR_DARK_GREEN      /* dark green color */
#define McuGDisplay_COLOR_BRIGHT_GREEN       McuSharpMemoryDisplay_COLOR_BRIGHT_GREEN    /* bright green color */
#define McuGDisplay_COLOR_BLUE               McuSharpMemoryDisplay_COLOR_BLUE            /* blue color */
#define McuGDisplay_COLOR_BRIGHT_BLUE        McuSharpMemoryDisplay_COLOR_BRIGHT_BLUE     /* bright blue color */
#define McuGDisplay_COLOR_DARK_BLUE          McuSharpMemoryDisplay_COLOR_DARK_BLUE       /* dark blue color */
#define McuGDisplay_COLOR_YELLOW             McuSharpMemoryDisplay_COLOR_YELLOW          /* yellow color */
#define McuGDisplay_COLOR_BRIGHT_YELLOW      McuSharpMemoryDisplay_COLOR_BRIGHT_YELLOW   /* bright yellow color */
#define McuGDisplay_COLOR_ORANGE             McuSharpMemoryDisplay_COLOR_ORANGE          /* orange color */
#define McuGDisplay_COLOR_GREY               McuSharpMemoryDisplay_COLOR_GREY            /* grey color */
#define McuGDisplay_COLOR_BRIGHT_GREY        McuSharpMemoryDisplay_COLOR_BRIGHT_GREY     /* bright grey color */

typedef McuSharpMemoryDisplay_PixelDim   McuGDisplay_PixelDim; /* Display specific type for a pixel coordinate. */
typedef McuSharpMemoryDisplay_PixelColor McuGDisplay_PixelColor; /* Display specific color type. */
typedef McuSharpMemoryDisplay_PixelCount McuGDisplay_PixelCount; /* Type able to hold the number of pixels for the display. */

/* wrappers for the low level display orientation enumeration and type */
typedef McuSharpMemoryDisplay_DisplayOrientation McuGDisplay_DisplayOrientation;
#define McuGDisplay_ORIENTATION_PORTRAIT     McuSharpMemoryDisplay_ORIENTATION_PORTRAIT
#define McuGDisplay_ORIENTATION_PORTRAIT180  McuSharpMemoryDisplay_ORIENTATION_PORTRAIT180
#define McuGDisplay_ORIENTATION_LANDSCAPE    McuSharpMemoryDisplay_ORIENTATION_LANDSCAPE
#define McuGDisplay_ORIENTATION_LANDSCAPE180 McuSharpMemoryDisplay_ORIENTATION_LANDSCAPE180


/* Landscape */

#define McuGDisplay_BUF_BYTE(x,y)  /* how to access a byte in the display buf[][] */ \
      McuSharpMemoryDisplay_DisplayBuf[y][(x)/8]
#define McuGDisplay_BUF_BYTE_PIXEL_BIT_NO(x,y) /* pixel bit number inside display buffer byte (0 is LSB, 7 MSB) */ \
      ((byte)(7-((x)%8)))

#define McuGDisplay_BUF_BYTE_PIXEL_MASK(x,y)  /* pixel mask for an individual bit inside a display buffer byte */ \
  (1<<McuGDisplay_BUF_BYTE_PIXEL_BIT_NO(x,y))

#define McuGDisplay_BUF_BYTE_GET_PIXEL(x,y)  /* extract a pixel */ \
  ((McuGDisplay_BUF_BYTE(x,y)&McuGDisplay_BUF_BYTE_PIXEL_MASK(x,y))>>McuGDisplay_BUF_BYTE_PIXEL_BIT_NO(x,y))

void McuGDisplay_Clear(void);
/*
** ===================================================================
**     Method      :  McuGDisplay_Clear (component GDisplay)
**     Description :
**         Clears the display buffer.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_SetPixel(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y);
/*
** ===================================================================
**     Method      :  McuGDisplay_SetPixel (component GDisplay)
**     Description :
**         Sets a pixel in the display buffer
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - Pixel x position
**         y               - Pixel y position
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_ClrPixel(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y);
/*
** ===================================================================
**     Method      :  McuGDisplay_ClrPixel (component GDisplay)
**     Description :
**         Clears a single pixel in the display.
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - Pixel x position.
**         y               - Pixel y position.
**     Returns     : Nothing
** ===================================================================
*/

#define McuGDisplay_UpdateFull()   McuSharpMemoryDisplay_UpdateFull()
/*
** ===================================================================
**     Method      :  McuGDisplay_UpdateFull (component GDisplay)
**     Description :
**         Updates the image on the display. This is needed in case the
**         display requires a periodic refresh. For display using
**         windowing, this function may be implemented as dummy stub,
**         as the display content already is written.
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_DrawFilledBox(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y, McuGDisplay_PixelDim width, McuGDisplay_PixelDim height, McuGDisplay_PixelColor color);
/*
** ===================================================================
**     Method      :  McuGDisplay_DrawFilledBox (component GDisplay)
**     Description :
**         Draws a rectangle box (filled)
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - x left upper coordinate
**         y               - y left upper coordinate
**         width           - Width in pixels
**         height          - Height in pixels
**         color           - color to be used to fill the box.
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_PutPixel(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y, McuGDisplay_PixelColor color);
/*
** ===================================================================
**     Method      :  McuGDisplay_PutPixel (component GDisplay)
**     Description :
**         
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - x coordinate
**         y               - y coordinate
**         color           - color to be used for the pixel
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_DrawBox(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y, McuGDisplay_PixelDim width, McuGDisplay_PixelDim height, McuGDisplay_PixelDim lineWidth, McuGDisplay_PixelColor color);
/*
** ===================================================================
**     Method      :  McuGDisplay_DrawBox (component GDisplay)
**     Description :
**         Draws a rectangle line box
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - x left upper coordinate
**         y               - y left upper coordinate
**         width           - width in pixels
**         height          - height in pixels
**         lineWidth       - width of the line
**         color           - color for the box
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_DrawMonoBitmap(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y, PIMAGE image, McuGDisplay_PixelColor pixelColor, McuGDisplay_PixelColor backgroundColor);
/*
** ===================================================================
**     Method      :  McuGDisplay_DrawMonoBitmap (component GDisplay)
**     Description :
**         Draws a B/W bitmap.
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - x position of left upper corner
**         y               - y position of left upper corner
**         image           - Pointer to image structure and
**                           information.
**         pixelColor      - Color to be used for pixels
**                           (pixel set)
**         backgroundColor - Color to be used
**                           for background (pixel not set)
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_DrawHLine(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y, McuGDisplay_PixelDim length, McuGDisplay_PixelColor color);
/*
** ===================================================================
**     Method      :  McuGDisplay_DrawHLine (component GDisplay)
**     Description :
**         Draws a horizontal line
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - x left upper coordinate
**         y               - y left upper coordinate
**         length          - Length of line in pixels
**         color           - color to be used to fill the box.
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_DrawVLine(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y, McuGDisplay_PixelDim length, McuGDisplay_PixelColor color);
/*
** ===================================================================
**     Method      :  McuGDisplay_DrawVLine (component GDisplay)
**     Description :
**         Draws a vertical line
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - x left upper coordinate
**         y               - y left upper coordinate
**         length          - Length of line in pixels
**         color           - color to be used to fill the box.
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_DrawBarChart(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y, McuGDisplay_PixelDim width, McuGDisplay_PixelDim height, byte *data, byte nofData, McuGDisplay_PixelColor barColor, byte borderWidth, McuGDisplay_PixelColor borderColor, byte borderSpace);
/*
** ===================================================================
**     Method      :  McuGDisplay_DrawBarChart (component GDisplay)
**     Description :
**         Draws a series of bars for a chart
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - upper left corner x coordinate
**         y               - upper left corner y coordinate
**         width           - Chart box width
**         height          - Chart box height
**       * data            - Pointer to data (series of % values
**                           from 0...100%)
**         nofData         - number of data bytes
**         barColor        - Color to be used for the bars.
**         borderWidth     - width of a border to be
**                           draw. Pass zero if there shall be no border.
**         borderColor     - Color to be used for the
**                           border (if borderWidth is not zero)
**         borderSpace     - Space to be used in pixels
**                           between border and bars.
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_DrawColorBitmap(McuGDisplay_PixelDim x, McuGDisplay_PixelDim y, PIMAGE image);
/*
** ===================================================================
**     Method      :  McuGDisplay_DrawColorBitmap (component GDisplay)
**     Description :
**         Draws a color bitmap. Pixel data is in 3-3-2 RGB format.
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - x position of left upper corner
**         y               - y position of left upper corner
**         image           - Pointer to image structure and
**                           information.
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_DrawLine(McuGDisplay_PixelDim xstart, McuGDisplay_PixelDim ystart, McuGDisplay_PixelDim xend, McuGDisplay_PixelDim yend, McuGDisplay_PixelColor color);
/*
** ===================================================================
**     Method      :  McuGDisplay_DrawLine (component GDisplay)
**     Description :
**         Draws a line using the Bresenham method
**     Parameters  :
**         NAME            - DESCRIPTION
**         xstart          - x start coordinate
**         ystart          - y start coordinate
**         xend            - x end coordinate
**         yend            - y end coordinate
**         color           - color to be used for the line
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_DrawCircle(McuGDisplay_PixelDim x0, McuGDisplay_PixelDim y0, McuGDisplay_PixelDim radius, McuGDisplay_PixelColor color);
/*
** ===================================================================
**     Method      :  McuGDisplay_DrawCircle (component GDisplay)
**     Description :
**         Draws a circle using the Bresenham method
**     Parameters  :
**         NAME            - DESCRIPTION
**         x0              - x start coordinate
**         y0              - y start coordinate
**         radius          - Radius of the circle
**         color           - color to be used for the line
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_Draw65kBitmap(McuGDisplay_PixelDim x1, McuGDisplay_PixelDim y1, McuGDisplay_PixelDim x2, McuGDisplay_PixelDim y2, word *bmp, bool compressed);
/*
** ===================================================================
**     Method      :  McuGDisplay_Draw65kBitmap (component GDisplay)
**     Description :
**         Draws a 65k color bitmap (compressed or uncompressed)
**     Parameters  :
**         NAME            - DESCRIPTION
**         x1              - left upper starting corner
**         y1              - left upper starting corner
**         x2              - right lower corner
**         y2              - right lower corner
**       * bmp             - Pointer to bitmap
**         compressed      - 
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_Draw256BitmapLow(McuGDisplay_PixelDim x1, McuGDisplay_PixelDim y1, McuGDisplay_PixelDim x2, McuGDisplay_PixelDim y2, byte *bmp, bool compressed);
/*
** ===================================================================
**     Method      :  McuGDisplay_Draw256BitmapLow (component GDisplay)
**     Description :
**         Draws a 256 color bitmap (compressed or uncompressed)
**     Parameters  :
**         NAME            - DESCRIPTION
**         x1              - left upper starting corner
**         y1              - left upper starting corner
**         x2              - right lower corner
**         y2              - right lower corner
**       * bmp             - Pointer to bitmap
**         compressed      - 
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_Draw256BitmapHigh(McuGDisplay_PixelDim x1, McuGDisplay_PixelDim y1, McuGDisplay_PixelDim x2, McuGDisplay_PixelDim y2, byte *bmp, McuGDisplay_PixelColor *ColorTable, bool compressed);
/*
** ===================================================================
**     Method      :  McuGDisplay_Draw256BitmapHigh (component GDisplay)
**     Description :
**         Draws a 256 color bitmap (compressed or uncompressed) with a
**         color table.
**     Parameters  :
**         NAME            - DESCRIPTION
**         x1              - left upper starting corner
**         y1              - left upper starting corner
**         x2              - right lower corner
**         y2              - right lower corner
**       * bmp             - Pointer to bitmap
**       * ColorTable      - Pointer to array of colors
**                           (color table)
**         compressed      - 
**     Returns     : Nothing
** ===================================================================
*/

#define McuGDisplay_UpdateRegion(x,y,w,h)   McuSharpMemoryDisplay_UpdateRegion(x,y,w,h)

/*
** ===================================================================
**     Method      :  McuGDisplay_UpdateRegion (component GDisplay)
**     Description :
**         Update a region of the display.
**     Parameters  :
**         NAME            - DESCRIPTION
**         x               - x coordinate
**         y               - y coordinate
**         w               - Width of the update region
**         h               - height of the update region
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_DrawFilledCircle(McuGDisplay_PixelDim x0, McuGDisplay_PixelDim y0, McuGDisplay_PixelDim radius, McuGDisplay_PixelColor color);
/*
** ===================================================================
**     Method      :  McuGDisplay_DrawFilledCircle (component GDisplay)
**     Description :
**         Draws a circle using the Bresenham method
**     Parameters  :
**         NAME            - DESCRIPTION
**         x0              - x start coordinate
**         y0              - y start coordinate
**         radius          - Radius of the circle
**         color           - fill color to be used
**     Returns     : Nothing
** ===================================================================
*/

#define McuGDisplay_GetWidth McuSharpMemoryDisplay_GetLongerSide
/*
** ===================================================================
**     Method      :  McuGDisplay_GetWidth (component GDisplay)
**     Description :
**         Returns the width of the display in pixels (in x direction)
**     Parameters  : None
**     Returns     :
**         ---             - pixel count
** ===================================================================
*/

#define McuGDisplay_GetHeight McuSharpMemoryDisplay_GetShorterSide
/*
** ===================================================================
**     Method      :  McuGDisplay_GetHeight (component GDisplay)
**     Description :
**         Returns the height of the display in pixels (in y direction)
**     Parameters  : None
**     Returns     :
**         ---             - pixel count
** ===================================================================
*/

#define McuGDisplay_GetLongerSide McuSharpMemoryDisplay_GetLongerSide
/*
** ===================================================================
**     Method      :  McuGDisplay_GetLongerSide (component GDisplay)
**     Description :
**         Returns the size of the longer side of the display
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

#define McuGDisplay_GetShorterSide McuSharpMemoryDisplay_GetShorterSide
/*
** ===================================================================
**     Method      :  McuGDisplay_GetShorterSide (component GDisplay)
**     Description :
**         Returns the size of the shorter side of the display
**     Parameters  : None
**     Returns     :
**         ---             - Error code
** ===================================================================
*/

void McuGDisplay_GetDisplay(void);
/*
** ===================================================================
**     Method      :  McuGDisplay_GetDisplay (component GDisplay)
**     Description :
**         Method used to reserve the display (for mutual exclusive
**         access)
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_GiveDisplay(void);
/*
** ===================================================================
**     Method      :  McuGDisplay_GiveDisplay (component GDisplay)
**     Description :
**         Returns the display after having it reserved with
**         GetDisplay()
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

void McuGDisplay_Init(void);
/*
** ===================================================================
**     Method      :  McuGDisplay_Init (component GDisplay)
**     Description :
**         
**     Parameters  : None
**     Returns     : Nothing
** ===================================================================
*/

/* END McuGDisplay. */

#endif
/* ifndef __McuGDisplay_H */
/*!
** @}
*/
/*
** ###################################################################
**
**     This file was created by Processor Expert 10.5 [05.21]
**     for the Freescale Kinetis series of microcontrollers.
**
** ###################################################################
*/
